name: food_delivery_app
description: "Food Delivery App"

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.1
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  infinite_scroll_pagination: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
